### ISSUE TITLE
IPFS in Web Browsers & Future of Browser Extensions

### ISSUE THREAD

**Issue by flyingzumwalt** [protocol/lab-week-unconf#23]
lead: @lidel and @kyledrake

**Comment by lgierth** [comment]
## WebExt now
- basic webextension works in ff and chrome
- supports ipfs:// and dweb: via redirect

## WebExt short/mid term future
- dnslink lookups enabled by default
  - currently very performance intensive
- opportunistic mirroring of web assets?

## WebExt long term future
- js-ipfs node in webextension
  - js-ipfs readiness
  - service-workers can only have requests initiated by same domain
    - foreign-fetch is whitelisting via HTTP header
      - in draft/discussion phase, no clean answer in next 3-6 months
  - we should participate in service-workers/foreign-fetch spec work
- proper ipfs:// and dweb: protocol with its own origin mechanism
  - prototype the protocol handlers API using the webextensions experiment toolkit
  - be the first here so we can set the agenda :)

## talking with mozilla
- sometimes really receptive
- sometimes flat out reject stuff (e.g. dns lookups)
- we should not be dismissive of all the innovation that has happened in the browser space
- the browser people are just a bit protective of what they've achieved
- it's good to have all our needs and questions documented well

## ipfs browser
- our announcements are taken pretty seriously by now, be very cautious with things like "we're starting a browser"
- we desperately need to proof the dweb UX to ourselves and others (e.g. mozilla)
- our own browser can be a huge timesink
  - which browsers succeed? chrome (google), edge (ms), firefox (20 years experience)
- david has done some work for ipfs:// in brave browser
  - check muon framework
- fork beaker?
  - would feel uncomfortable, like stomping on an indy developer
  - beaker is super awesome
- precedent: tor browser
  - maybe frame protocol handlers similarly: a delta of changes
- do not fall in the same trap that dat and beaker did. they focus solely in their browser and miss a ton of opportunity by not planning how to integrate with other browsers

**Comment by lgierth** [comment]
We went over time pretty well.

What we didn't get to:

- API security / ACLs / tokens

**Comment by lidel** [comment]
Action Items for Browser Extension in near future:

- Polish UX for what we already have
  - Intuitive GUI with feedback for things like upload progress (https://github.com/ipfs/js-ipfs-api/pull/604 ?)
  - Recreate test suite (https://github.com/ipfs/ipfs-companion/issues/145) and run it against both Firefox and Chrome
   -  improve dnslink lookup performance so that it can be enabled by default (https://github.com/ipfs/ipfs-companion/issues/69)
- Push toward proper `ipfs://` and `dweb:`  protocol with its own _programmable_ Origin mechanism (https://github.com/ipfs/ipfs-companion/issues/164)
  - prototype the protocol handlers API using the [WebExtensions Experiments](https://webextensions-experiments.readthedocs.io/en/latest/) toolkit
  - attach it to  [Bug 1271553 - Add ability to implement programmable custom protocol handler](https://bugzilla.mozilla.org/show_bug.cgi?id=1271553) (be the first here so we can set the agenda and provide preferred implementation for it)

**Comment by lidel** [comment]
Let's try to re-frame session result as as OKR below (feel free to edit it)

###  OKR (draft)

Objective: **Web Browsers users have access to the Distributed Web (by default)**
Key Results on the road to that:
- **Browser extension enables users to load IPFS content using own IPFS node**
  - [ipfs-companion](https://github.com/ipfs/ipfs-companion) + go-ipfs
  - WIP: detect and re-route loading of assets identified by multihash/CID on any site
  - near term focus: polish and sustainability (getting accepted to AMO, cross-browser tests etc)
- **Browser extension enables users to load IPFS content without any additional software** 
  - [ipfs-companion](https://github.com/ipfs/ipfs-companion) + embedded js-ipfs
  - Research the "Service Worker workaround"
  - Prototype missing WebExtension APIs (protocol handlers, response proxying/spoofing) and try to get them accepted by Mozilla
- **Browser supports IPFS out-of-the-box, without any extension**
  - Create PoC integrations and experiments that demonstrate viability of such integration (example:  https://github.com/diasdavid/browser-laptop/pull/1#discussion_r135454765) 
  - Use all the above to advocate our case to browser vendors

**Comment by lidel** [comment]
I've created a PR with notes on identified roadblocks for having  "ipfs-companion + embedded js-ipfs": 
https://github.com/ipfs/in-web-browsers/pull/60
